services:
  stock-app-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-app-node
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_URL: mongodb://stock-app-mongo:27017/trading_desk
      STATIC_DIR: /app/html
    depends_on:
      - stock-app-mongo
    ports:
      - "3002:3000"
    networks:
      - stock-app-internal
      - reverse-proxy

  stock-app-mongo:
    image: mongo:7
    container_name: stock-app-mongo
    restart: unless-stopped
    volumes:
      - stock-app-mongo-data:/data/db
    networks:
      - stock-app-internal

volumes:
  stock-app-mongo-data:

networks:
  stock-app-internal:
    name: stock-app-internal
  reverse-proxy:
    name: reverse-proxy
    external: true
